import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CategoryProvider} from '@/context/CategoryContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next my App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto max-w-screen-lg min-h-screen flex flex-col items-center p-24">
          <CategoryProvider>
          {children}

          </CategoryProvider>
         
        </div>
      </body>
    </html>
  );
}
